---
#
#apiVersion: "k8s.cni.cncf.io/v1"
#kind: NetworkAttachmentDefinition
#metadata:
#  name: pod-gui-network
#spec:
#  tenant_id: e93adb34143c42b8847f009dba9413a7
#  network_id: b9d1a34d-7c82-4cb5-9a33-ab6f3d7e54c2
#  subnets:
#    - name: v4-sub1
#      subnet_id: 845b2d9b-b865-46a5-a794-2ead6cee2fe0
#      enable_dhcp: true
#  static_ip: false

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  preserveUnknownFields: false
  group: k8s.cni.cncf.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            NetworkAttachmentDefinition is a Kubernetes Custom Resource Definition (CRD) that is used
            to define custom network configurations for Pods.
          properties:
            spec:
              type: object
              description: Configuration Specification for the NetworkAttachmentDefinition.
              properties:
                tenant_id:
                  type: string
                  nullable: true
                network_id:
                  type: string
                  nullable: true
                segmentation_id:
                  type: integer
                  nullable: true
                network_type:
                  type: string
                  nullable: true
                physical_network:
                  type: string
                  nullable: true
                create_at:
                  type: string
                  nullable: true
                static_ip:
                  type: boolean
                  nullable: true
                warm:
                  type: boolean
                  nullable: true
                release_after:
                  type: string
                  nullable: true
                router_external:
                  type: boolean
                  nullable: true
                subnets:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        nullable: true
                      subnet_id:
                        type: string
                        nullable: true
                      gateway_ip:
                        type: string
                        nullable: true
                      cidr:
                        type: string
                        nullable: true
                      ip_version:
                        type: integer
                        nullable: true
                      enable_dhcp:
                        type: boolean
                        nullable: true
                      dns_nameservers:
                        type: array
                        nullable: true
                        items:
                          type: string
                      host_routes:
                        type: array
                        nullable: true
                        items:
                          type: object
                          properties:
                            nexthop:
                              type: string
                              nullable: true
                            destination:
                              type: string
                              nullable: true
                      allocation_pools:
                        type: array
                        nullable: true
                        items:
                          type: object
                          properties:
                            start:
                              type: string
                              nullable: true
                            end:
                              type: string
                              nullable: true
  scope: Cluster
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
      - net-attach-def
---
